global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - /etc/prometheus/rules/alerts.rules

scrape_configs: # FastAPI application metrics
  - job_name: "fastapi-app"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:5050"]
        labels:
          group: "fastapi-app"
          service: "weather-prediction-api"
  # Prometheus itself
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["prometheus:9090"]
        labels:
          group: "prometheus"

  # Node exporter for system metrics
  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          group: "system-metrics"
