auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://alertmanager:9093
  storage:
    type: local
    local:
      directory: /loki/rules

limits_config:
  retention_period: 7d
  enforce_metric_name: false
  reject_old_samples: false
  reject_old_samples_max_age: 336h
  creation_grace_period: 2d
  max_entries_limit_per_query: 5000

compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

analytics:
  reporting_enabled: false

# Syslog input configuration
syslog:
  listen_address: 0.0.0.0:1514
  listen_protocol: tcp
  labels:
    job: "syslog"
  use_incoming_timestamp: true
