global:
  resolve_timeout: 5m
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "mlops.alerts@gmail.com"
  smtp_auth_username: "mlops.alerts@gmail.com"
  smtp_auth_password: "${SMTP_PASSWORD}"
  smtp_require_tls: true

route:
  group_by: ["alertname", "job"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: "email-notifications"
  routes:
    - match:
        severity: critical
      receiver: "email-notifications"
      continue: true
    - match:
        severity: warning
      receiver: "email-notifications"

receivers:
  - name: "email-notifications"
    email_configs:
      - to: "admin@example.com"
        send_resolved: true
        html: |
          {{ if eq .Status "firing" }}
            <h1 style="color: #FF0000">{{ .CommonLabels.alertname }}</h1>
          {{ else }}
            <h1 style="color: #00FF00">{{ .CommonLabels.alertname }} - RESOLVED</h1>
          {{ end }}
          <p><b>Status:</b> {{ .Status }}</p>
          <p><b>Summary:</b> {{ .CommonAnnotations.summary }}</p>
          <p><b>Description:</b> {{ .CommonAnnotations.description }}</p>
          <p><b>Start Time:</b> {{ .StartsAt }}</p>
          {{ if ne .Status "firing" }}
            <p><b>End Time:</b> {{ .EndsAt }}</p>
          {{ end }}
          <p><b>Labels:</b></p>
          <ul>
          {{ range .CommonLabels.SortedPairs }}
            <li>{{ .Name }}: {{ .Value }}</li>
          {{ end }}
          </ul>
          <p><a href="http://localhost:9090/alerts">View in Prometheus</a></p>
          <p><a href="http://localhost:3000/d/weather/weather-prediction-api-dashboard">View in Grafana</a></p>

  # Slack notification example (uncomment and configure to enable)
  # - name: 'slack-notifications'
  #   slack_configs:
  #     - api_url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'
  #       channel: '#alerts'
  #       send_resolved: true
  #       title: '{{ .CommonLabels.alertname }}'
  #       text: "{{ range .Alerts }}*Status:* {{ .Status }}\n*Summary:* {{ .Annotations.summary }}\n*Description:* {{ .Annotations.description }}\n{{ end }}"

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "job"]
