version: '3.8'

# Weather Prediction API Monitoring and Logging Stack
# This docker-compose file defines all monitoring and logging services

services:
  # Prometheus - Time series database for metrics collection
  # Accessible at http://localhost:9090
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules:/etc/prometheus/rules
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    extra_hosts:
      - "host.docker.internal:host-gateway" # Allows access to host machine
    networks:
      - monitoring-network

  # Node Exporter - System metrics collector
  # Provides CPU, memory, disk, and network metrics
  # Accessible at http://localhost:9100/metrics
  node-exporter:
    image: prom/node-exporter:v1.6.1
    container_name: node-exporter
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring-network

  # AlertManager - Handles alerts from Prometheus
  # Routes notifications to configured receivers (email, etc)
  # Accessible at http://localhost:9093
  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: alertmanager
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitoring-network
    
  # Grafana - Visualization platform for metrics
  # Provides dashboards for system and API metrics
  # Accessible at http://localhost:3000 (login: admin/admin)
  grafana:
    image: grafana/grafana:10.0.3
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json
      - ./grafana/dashboard-provider.yml:/etc/grafana/provisioning/dashboards/dashboard-provider.yml
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_COOKIE_SAMESITE=none
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitoring-network
    depends_on:
      - prometheus

  # Fluent Bit - Log collector and forwarder
  # Collects logs from system and application sources
  # Management interface accessible at http://localhost:2020
  fluent-bit:
    image: fluent/fluent-bit:2.1.9
    container_name: fluent-bit
    restart: always
    ports:
      - "2020:2020"
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
      - ./app:/opt/app:ro
      - fluent_bit_data:/tmp
      - ./logs:/var/log/app:rw
    environment:
      - FLB_LOG_LEVEL=info
    command:
      - /fluent-bit/bin/fluent-bit
      - -c
      - /fluent-bit/etc/fluent-bit.conf
      - -v
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitoring-network
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

# Shared network for all monitoring and logging services
networks:
  monitoring-network:
    driver: bridge

# Persistent volumes for data storage
volumes:
  # Stores metrics data from Prometheus
  prometheus_data:
  # Stores alert history and configurations
  alertmanager_data:
  # Stores Grafana dashboards, users, and other configurations
  grafana_data:
  # Stores Fluent Bit state and buffers
  fluent_bit_data:
